version: "3"
services:
    db:
        image: mongo:4.1.8-xenial
        restart: unless-stopped
        env_file: .env
        environment:
            - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
            - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
        volumes:
            - dbdata:/data/db
        ports: 
            - 7200:27017
    
    users:
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 3000:3000
            - 9229:9229
        volumes:
            - ./:/usr/src/app
        tty: true

volumes:
    dbdata: